{
 "title": "Bots",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"apigateway\", namespace=\"army\", status=~\"2.+\"}[15m]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"apigateway\", namespace=\"army\", status=~\"4.+\"}[15m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"apigateway\", namespace=\"army\", status=~\"5.+\"}[15m]))",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "CPU usage (cron-scheduler)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"army\", container=\"cron-scheduler\"}[15m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"army\", container=\"cron-scheduler\", resource=\"cpu\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"army\", container=\"cron-scheduler\", resource=\"cpu\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory usage (cron-scheduler)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"army\", container=\"cron-scheduler\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"army\", container=\"cron-scheduler\", resource=\"memory\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"army\", container=\"cron-scheduler\", resource=\"memory\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "CPU usage (apigateway)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"army\", container=\"apigateway\"}[15m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"army\", container=\"apigateway\", resource=\"cpu\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"army\", container=\"apigateway\", resource=\"cpu\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory usage (apigateway)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"army\", container=\"apigateway\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"army\", container=\"apigateway\", resource=\"memory\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"army\", container=\"apigateway\", resource=\"memory\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "CPU usage (clickhouse)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"army\", container=\"clickhouse\"}[15m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"army\", container=\"clickhouse\", resource=\"cpu\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"army\", container=\"clickhouse\", resource=\"cpu\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory usage (clickhouse)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"army\", container=\"clickhouse\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"army\", container=\"clickhouse\", resource=\"memory\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"army\", container=\"clickhouse\", resource=\"memory\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "CPU usage (staticmap-api)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"army\", container=\"staticmap-api\"}[15m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"army\", container=\"staticmap-api\", resource=\"cpu\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"army\", container=\"staticmap-api\", resource=\"cpu\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory usage (static-map)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"army\", container=\"staticmap-api\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"army\", container=\"staticmap-api\", resource=\"memory\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"army\", container=\"staticmap-api\", resource=\"memory\"})",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "ships-finder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Count pod(ships-finder)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{namespace='army', deployment=\"ships-finder\"})"
    }
   ]
  },
  {
   "title": "ships_finder_http_request_duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ships_finder_http_request_duration_seconds_bucket[15m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ships_finder_http_request_duration_seconds_bucket[15m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ships_finder_http_request_duration_seconds_bucket[15m])) by (le))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "CPU usage (ships-finder)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"army\", container=\"ships-finder\"}[15m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"army\", container=\"ships-finder\", resource=\"cpu\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"army\", container=\"ships-finder\", resource=\"cpu\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Restart pod(ships-finder)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace='army', pod=~\"ships-finder-.{8,10}-.{5}\"}[15m]))"
    }
   ]
  },
  {
   "title": "ships_finder_http_request_count by code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 53 },
   "targets": [
    {
     "expr": "sum(increase(ships_finder_http_request_duration_seconds_count{code=~'2..'}[24h]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(rate(ships_finder_http_request_duration_seconds_count{code=~'4..'}[15m]))"
    },
    {
     "expr": "sum(rate(ships_finder_http_request_duration_seconds_count{code=~'5..'}[15m]))"
    }
   ]
  },
  {
   "title": "Memory usage (ships-finder)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"army\", container=\"ships-finder\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"army\", container=\"ships-finder\", resource=\"memory\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"army\", container=\"ships-finder\", resource=\"memory\"})",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "notams-bot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Count pod(notams-bot)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{namespace='army', deployment=\"notams-bot\"})"
    }
   ]
  },
  {
   "title": "notams_bot_http_request_duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(notams_bot_http_request_duration_seconds_bucket{pod=~\"notams-bot-.{9,10}-.{5}\"}[15m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(notams_bot_http_request_duration_seconds_bucket{pod=~\"notams-bot-.{9,10}-.{5}\"}[15m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(notams_bot_http_request_duration_seconds_bucket{pod=~\"notams-bot-.{9,10}-.{5}\"}[15m])) by (le))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "CPU usage (notams-bot)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"army\", container=\"notams-bot\"}[15m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"army\", container=\"notams-bot\", resource=\"cpu\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"army\", container=\"notams-bot\", resource=\"cpu\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Restart pod(notams-bot)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace='army', pod=~\"notams-bot-.{8,10}-.{5}\"}[15m]))"
    }
   ]
  },
  {
   "title": "notams_bot_http_request_count by code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 68 },
   "targets": [
    {
     "expr": "sum(increase(notams_bot_http_request_duration_seconds_count{code=~'2..'}[24h]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(rate(notams_bot_http_request_duration_seconds_count{code=~'4..'}[15m]))"
    },
    {
     "expr": "sum(rate(notams_bot_http_request_duration_seconds_count{code=~'5..'}[15m]))"
    }
   ]
  },
  {
   "title": "Memory usage (notams-bot)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"army\", container=\"notams-bot\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"army\", container=\"notams-bot\", resource=\"memory\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"army\", container=\"notams-bot\", resource=\"memory\"})",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}